// Code generated by "stringer -type=Sector -output=sector_type_string.go"; DO NOT EDIT.

package quadstate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C-0]
	_ = x[N-1]
	_ = x[NE-2]
	_ = x[E-3]
	_ = x[SE-4]
	_ = x[S-5]
	_ = x[SW-6]
	_ = x[W-7]
	_ = x[NW-8]
	_ = x[SectorSize-9]
}

const _Sector_name = "CNNEESESSWWNWSectorSize"

var _Sector_index = [...]uint8{0, 1, 2, 4, 5, 7, 8, 10, 11, 13, 23}

func (i Sector) String() string {
	if i < 0 || i >= Sector(len(_Sector_index)-1) {
		return "Sector(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Sector_name[_Sector_index[i]:_Sector_index[i+1]]
}
