// generated by stringer -type=Quad -output=quadrant_string.go; DO NOT EDIT

package coord

import "fmt"

const _Quad_name = "QUAD_NWQUAD_NEQUAD_SEQUAD_SW"

var _Quad_index = [...]uint8{0, 7, 14, 21, 28}

func (i Quad) String() string {
	if i < 0 || i+1 >= Quad(len(_Quad_index)) {
		return fmt.Sprintf("Quad(%d)", i)
	}
	return _Quad_name[_Quad_index[i]:_Quad_index[i+1]]
}
