// generated by stringer -type=CollisionType -output=collision_type_string.go; DO NOT EDIT

package coord

import "fmt"

const _CollisionType_name = "CT_NONECT_HEAD_TO_HEADCT_FROM_SIDECT_A_INTO_BCT_A_INTO_B_FROM_SIDECT_SWAPCT_SAME_ORIGCT_SAME_ORIG_PERPCT_SAME_ORIG_DESTCT_CELL_DESTCT_CELL_ORIG"

var _CollisionType_index = [...]uint8{0, 7, 22, 34, 45, 66, 73, 85, 102, 119, 131, 143}

func (i CollisionType) String() string {
	if i < 0 || i+1 >= CollisionType(len(_CollisionType_index)) {
		return fmt.Sprintf("CollisionType(%d)", i)
	}
	return _CollisionType_name[_CollisionType_index[i]:_CollisionType_index[i+1]]
}
