// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package coord

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[North-0]
	_ = x[N-0]
	_ = x[East-1]
	_ = x[E-1]
	_ = x[South-2]
	_ = x[S-2]
	_ = x[West-3]
	_ = x[W-3]
}

const _Direction_name = "NorthEastSouthWest"

var _Direction_index = [...]uint8{0, 5, 9, 14, 18}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
