// Code generated by "stringer -type=Quad -output=quadrant_string.go"; DO NOT EDIT.

package coord

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NW-0]
	_ = x[NE-1]
	_ = x[SE-2]
	_ = x[SW-3]
}

const _Quad_name = "NWNESESW"

var _Quad_index = [...]uint8{0, 2, 4, 6, 8}

func (i Quad) String() string {
	if i < 0 || i >= Quad(len(_Quad_index)-1) {
		return "Quad(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Quad_name[_Quad_index[i]:_Quad_index[i+1]]
}
