// generated by stringer -type=PacketType; DO NOT EDIT

package encoding

import "fmt"

const _PacketType_name = "PT_DISCONNECTPT_CONNECTPT_HEARTBEATPT_MESSAGEPT_JSONPT_EVENTPT_ACKPT_ERRORPT_NOOPPT_SIZE"

var _PacketType_index = [...]uint8{0, 13, 23, 35, 45, 52, 60, 66, 74, 81, 88}

func (i PacketType) String() string {
	if i < 0 || i+1 >= PacketType(len(_PacketType_index)) {
		return fmt.Sprintf("PacketType(%d)", i)
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
