// generated by stringer -type=WorldStateType -output=world_state_type_string.go; DO NOT EDIT

package rpg2d

import "fmt"

const _WorldStateType_name = "ST_FULLST_DIFF"

var _WorldStateType_index = [...]uint8{0, 7, 14}

func (i WorldStateType) String() string {
	if i < 0 || i+1 >= WorldStateType(len(_WorldStateType_index)) {
		return fmt.Sprintf("WorldStateType(%d)", i)
	}
	return _WorldStateType_name[_WorldStateType_index[i]:_WorldStateType_index[i+1]]
}
