// generated by stringer -type=EncodedType; DO NOT EDIT

package net

import "fmt"

const _EncodedType_name = "ET_ERRORET_PROTOCOL_ERRORET_DISCONNECTET_CONNECT_ACTORET_CONNECTED_ACTORET_WORLD_STATEET_WORLD_STATE_DIFFET_EXTEND"

var _EncodedType_index = [...]uint8{0, 8, 25, 38, 54, 72, 86, 105, 114}

func (i EncodedType) String() string {
	if i < 0 || i+1 >= EncodedType(len(_EncodedType_index)) {
		return fmt.Sprintf("EncodedType(%d)", i)
	}
	return _EncodedType_name[_EncodedType_index[i]:_EncodedType_index[i+1]]
}
