// Code generated by "stringer -type=EncodedType"; DO NOT EDIT

package net

import "fmt"

const _EncodedType_name = "ET_ERRORET_PROTOCOL_ERRORET_DISCONNECTET_USER_LOGIN_REQUESTET_USER_LOGIN_FAILEDET_USER_LOGIN_SUCCESSET_USER_CREATE_SUCCESSET_ACTORSET_SELECT_ACTORET_SELECT_ACTOR_SUCCESSET_CREATE_ACTOR_SUCCESSET_EXTEND"

var _EncodedType_index = [...]uint8{0, 8, 25, 38, 59, 79, 100, 122, 131, 146, 169, 192, 201}

func (i EncodedType) String() string {
	if i < 0 || i >= EncodedType(len(_EncodedType_index)-1) {
		return fmt.Sprintf("EncodedType(%d)", i)
	}
	return _EncodedType_name[_EncodedType_index[i]:_EncodedType_index[i+1]]
}
